from . import db
from flask_login import UserMixin
from datetime import datetime


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    category = db.Column(db.String(16))


class QRCode(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    code = db.Column(db.String(256), unique=True, nullable=False)
    name = db.Column(db.String(100), nullable=False)
    date_created = db.Column(db.DateTime, default=datetime.utcnow)
    latitude = db.Column(db.Float, nullable=False)
    longitude = db.Column(db.Float, nullable=False)
    used = db.Column(db.Boolean, default=False)


class LabTest(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    sample_date = db.Column(db.Date, nullable=False)
    analysis_date = db.Column(db.Date)
    location = db.Column(db.String(100), default="Nahal Kofer")
    ph = db.Column(db.Float)
    ph_2 = db.Column(db.Float)
    ph_average = db.Column(db.Float)
    ntu = db.Column(db.Float)
    ntu_2 = db.Column(db.Float)
    ave = db.Column(db.Float)
    hardness = db.Column(db.Float)
    ts_mg = db.Column(db.Float)
    ts_mg_2 = db.Column(db.Float)
    ave_ts = db.Column(db.Float)
    ts_smg = db.Column(db.Float)
    ts_smg_2 = db.Column(db.Float)
    ave_tss = db.Column(db.Float)
    fs_smg = db.Column(db.Float)
    fs_smg_2 = db.Column(db.Float)
    ave_fss = db.Column(db.Float)
    vs_smg = db.Column(db.Float)
    vs_smg_2 = db.Column(db.Float)
    ave_vss = db.Column(db.Float)
    td_smg = db.Column(db.Float)
    td_smg_2 = db.Column(db.Float)
    ave_tds = db.Column(db.Float)
    tp_mg = db.Column(db.Float)
    tp_mg_2 = db.Column(db.Float)
    ave_tp = db.Column(db.Float)
    tn = db.Column(db.Float)
    tn_2 = db.Column(db.Float)
    ave_tn = db.Column(db.Float)
    cod = db.Column(db.Float)
    cod_2 = db.Column(db.Float)
    ave_cod = db.Column(db.Float)
    nh4 = db.Column(db.Float)
    nh4_2 = db.Column(db.Float)
    ave_nh4 = db.Column(db.Float)
    po4p = db.Column(db.Float)
    po4p_2 = db.Column(db.Float)
    ave_po4 = db.Column(db.Float)
    no2 = db.Column(db.Float)
    no2_2 = db.Column(db.Float)
    ave_no2 = db.Column(db.Float)
    no3 = db.Column(db.Float)
    no3_2 = db.Column(db.Float)
    ave_no3 = db.Column(db.Float)
    bod = db.Column(db.Boolean)
    bod2 = db.Column(db.Boolean)
