from . import db
from flask_login import UserMixin


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    category = db.Column(db.String(16))


class LabTest(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    sample_date = db.Column(db.Date, nullable=False)
    analysis_date = db.Column(db.Date)
    ph = db.Column(db.Integer)
    ph_2 = db.Column(db.Integer)
    ph_average = db.Column(db.Integer)
    ntu = db.Column(db.Integer)
    ntu_2 = db.Column(db.Integer)
    ave = db.Column(db.Integer)
    hardness = db.Column(db.Integer)
    ts_mg = db.Column(db.Integer)
    ts_mg_2 = db.Column(db.Integer)
    ave_ts = db.Column(db.Integer)
    ts_smg = db.Column(db.Integer)
    ts_smg_2 = db.Column(db.Integer)
    ave_tss = db.Column(db.Integer)
    fs_smg = db.Column(db.Integer)
    fs_smg_2 = db.Column(db.Integer)
    ave_fss = db.Column(db.Integer)
    vs_smg = db.Column(db.Integer)
    vs_smg_2 = db.Column(db.Integer)
    ave_vss = db.Column(db.Integer)
    td_smg = db.Column(db.Integer)
    td_smg_2 = db.Column(db.Integer)
    ave_tds = db.Column(db.Integer)
    tp_mg = db.Column(db.Integer)
    tp_mg_2 = db.Column(db.Integer)
    ave_tp = db.Column(db.Integer)
    tn = db.Column(db.Integer)
    tn_2 = db.Column(db.Integer)
    ave_tn = db.Column(db.Integer)
    cod = db.Column(db.Integer)
    cod_2 = db.Column(db.Integer)
    ave_cod = db.Column(db.Integer)
    nh4 = db.Column(db.Integer)
    nh4_2 = db.Column(db.Integer)
    ave_nh4 = db.Column(db.Integer)
    po4p = db.Column(db.Integer)
    po4p_2 = db.Column(db.Integer)
    ave_po4 = db.Column(db.Integer)
    no2 = db.Column(db.Integer)
    no2_2 = db.Column(db.Integer)
    ave_no2 = db.Column(db.Integer)
    no3 = db.Column(db.Integer)
    no3_2 = db.Column(db.Integer)
    ave_no3 = db.Column(db.Integer)
    bod = db.Column(db.Boolean)
    bod2 = db.Column(db.Boolean)
